/**
 * Realistic 1CS API response mocks.
 *
 * These match the shapes returned by the @defuse-protocol/one-click-sdk-typescript
 * SDK methods: getQuote(), submitDepositTx(), getExecutionStatus().
 */

import type { QuoteResponseRecord } from "../types.js";
import type { StatusPollResult, DepositNotifyResult } from "../settler.js";

// ═══════════════════════════════════════════════════════════════════════
// Deposit address (the key binding between x402 payTo and 1CS)
// ═══════════════════════════════════════════════════════════════════════

/**
 * A realistic 1CS deposit address.
 * In production, this is generated by 1CS for each quote.
 */
export const MOCK_DEPOSIT_ADDRESS = "0x7a16fF8270133F063aAb6C9977183D9e72835428";

// ═══════════════════════════════════════════════════════════════════════
// Quote response
// ═══════════════════════════════════════════════════════════════════════

/**
 * Build a realistic 1CS QuoteResponse (as stored in SwapState.quoteResponse).
 *
 * Represents an EXACT_OUTPUT quote: merchant wants 10 USDC on the configured
 * destination chain, buyer pays ~10.50 USDC on Base (includes fee + slippage).
 *
 * To test a different destination chain, override `quoteRequest`:
 * ```typescript
 * mockQuoteResponse({
 *   quoteRequest: {
 *     ...mockQuoteResponse().quoteRequest,
 *     destinationAsset: DESTINATION_PRESETS.arbitrum.merchantAssetOut,
 *     recipient: DESTINATION_PRESETS.arbitrum.merchantRecipient,
 *   },
 * });
 * ```
 */
export function mockQuoteResponse(
  overrides: Partial<QuoteResponseRecord> = {},
): QuoteResponseRecord {
  const deadline = new Date(Date.now() + 10 * 60 * 1000); // 10 min from now

  return {
    correlationId: "corr-a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    timestamp: new Date().toISOString(),
    signature: "mock-1cs-quote-signature-base64",
    quoteRequest: {
      dry: false,
      swapType: "EXACT_OUTPUT",
      slippageTolerance: 50,
      originAsset: "nep141:base-0x833589fcd6edb6e08f4c7c32d4f71b54bda02913.omft.near",
      depositType: "ORIGIN_CHAIN",
      destinationAsset: "nep141:17208628f84f5d6ad33f0da3bbbeb27ffcb398eac501a31bd6ad2011e36133a1",
      amount: "10000000",
      refundTo: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
      refundType: "ORIGIN_CHAIN",
      recipient: "merchant.near",
      recipientType: "DESTINATION_CHAIN",
      deadline: deadline.toISOString(),
    },
    quote: {
      depositAddress: MOCK_DEPOSIT_ADDRESS,
      amountIn: "10500000",           // 10.50 USDC — what the buyer signs for
      amountInFormatted: "10.50",
      amountInUsd: "10.50",
      minAmountIn: "10200000",         // 10.20 USDC — minimum accepted
      amountOut: "10000000",           // 10.00 USDC — what merchant receives
      amountOutFormatted: "10.00",
      amountOutUsd: "10.00",
      minAmountOut: "9950000",         // 9.95 USDC — slippage floor
      deadline: deadline.toISOString(),
      timeWhenInactive: new Date(deadline.getTime() + 5 * 60 * 1000).toISOString(),
      timeEstimate: 30,                // ~30 seconds estimated settlement
    },
    ...overrides,
  };
}

// ═══════════════════════════════════════════════════════════════════════
// Deposit notification response
// ═══════════════════════════════════════════════════════════════════════

/**
 * Response from POST /v0/deposit/submit after notifying 1CS of the tx hash.
 */
export function mockDepositNotifyResponse(
  overrides: Partial<DepositNotifyResult> = {},
): DepositNotifyResult {
  return {
    status: "KNOWN_DEPOSIT_TX",
    correlationId: "corr-a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    ...overrides,
  };
}

// ═══════════════════════════════════════════════════════════════════════
// Status polling responses
// ═══════════════════════════════════════════════════════════════════════

/**
 * A typical happy-path status polling sequence.
 *
 * In production, 1CS transitions: KNOWN_DEPOSIT_TX → PROCESSING → SUCCESS.
 * The buyer waits ~30s total.
 *
 * @param options.destinationTxHash — Override the destination chain tx hash.
 * @param options.destinationExplorerUrl — Override the destination chain explorer URL
 *   (defaults to nearblocks.io; use e.g. "https://arbiscan.io/tx/" for Arbitrum).
 */
export function mockHappyPathStatusSequence(options: {
  destinationTxHash?: string;
  destinationExplorerUrl?: string;
} = {}): StatusPollResult[] {
  const destHash = options.destinationTxHash ?? "9XzKqRuAfcE7vWsH3bJpNmD4yT8gFwCeL2xYnG5oU6k";
  const destExplorerUrl = options.destinationExplorerUrl ?? `https://nearblocks.io/txns/${destHash}`;

  return [
    { status: "KNOWN_DEPOSIT_TX" },
    { status: "PROCESSING" },
    {
      status: "SUCCESS",
      swapDetails: {
        originChainTxHashes: [
          {
            hash: "0xf1e2d3c4b5a697f8e9d0c1b2a3948576061728394a5b6c7d8e9f0a1b2c3d4e5f",
            explorerUrl: "https://basescan.org/tx/0xf1e2d3c4b5a697f8e9d0c1b2a3948576061728394a5b6c7d8e9f0a1b2c3d4e5f",
          },
        ],
        destinationChainTxHashes: [
          {
            hash: destHash,
            explorerUrl: destExplorerUrl,
          },
        ],
        amountIn: "10500000",
        amountOut: "10000000",
      },
    },
  ];
}

/**
 * A failed swap sequence (e.g., liquidity dried up during settlement).
 */
export function mockFailedStatusSequence(): StatusPollResult[] {
  return [
    { status: "KNOWN_DEPOSIT_TX" },
    { status: "PROCESSING" },
    {
      status: "FAILED",
      swapDetails: {
        originChainTxHashes: [
          {
            hash: "0xf1e2d3c4b5a697f8e9d0c1b2a3948576061728394a5b6c7d8e9f0a1b2c3d4e5f",
            explorerUrl: "https://basescan.org/tx/0xf1e2d3c4b5a697f8e9d0c1b2a3948576061728394a5b6c7d8e9f0a1b2c3d4e5f",
          },
        ],
        refundedAmount: "10500000",
      },
    },
  ];
}

/**
 * A refunded swap sequence (1CS returned funds to refundTo).
 */
export function mockRefundedStatusSequence(): StatusPollResult[] {
  return [
    { status: "PENDING_DEPOSIT" },
    { status: "INCOMPLETE_DEPOSIT" },
    {
      status: "REFUNDED",
      swapDetails: {
        originChainTxHashes: [],
        refundedAmount: "10500000",
      },
    },
  ];
}

// `mockTerminalStatus` used to live here as a one-shot helper returning
// a single `StatusPollResult`. No test imported it — status sequences
// are always built via `mockHappyPathStatusSequence` or inline arrays
// in the tests that need terminal responses. Removed to keep the mock
// surface honest.
